Js file div integration
AdExNetwork/adex-adview-manager pull request #86
Opened 2020-12-03 12:25 UTC by rori4

Issue: option to integrate through JS + divs (Google Ad Manager) #46
- integrate through JS + divs
- also can use the iframe as before. If it doesn't find params for the container it uses `location.hash.slice(1)` as before

The divs are defined like 
```
    <div
      class="adex-container" params="%7B%22options%22%3A%7B%22publisherAddr%22%3A%220xD038C398795698133a7D556F49e3ffed18958ef5%22%2C%22whitelistedTokens%22%3A%5B%220x6B175474E89094C44Da98b954EedeAC495271d0F%22%5D%2C%22whitelistedType%22%3A%22legacy_300x100%22%2C%22randomize%22%3Atrue%2C%22targeting%22%3A%5B%5D%2C%22width%22%3A%22300%22%2C%22height%22%3A%22100%22%2C%22minPerImpression%22%3A%220%22%2C%22fallbackUnit%22%3A%22QmeXdTE6QRVpUAPPoFCGzeCvwVCMtTxUVE1fiH3AGGQWsV%22%2C%22marketSlot%22%3A%22QmNY6Hx8ZtYftiXdeT6F23ncyjAsgAjMgtU7453PCMHM14%22%7D%7D"
    ></div>
```
and the params attribute is used to fill the div.

You can check an integration example by running `npm run example-with-js`

Thoughts?

2020-12-03 14:46 UTC, Ivshti requested changes
We have to discuss this further because of two issues:
- this delays the loading until the DOM is ready which will make loading slower with the default iframe setup
- when adex is running from a separate hsot, validators might reject the requests - but this has to be doube checked

2020-12-03 16:47 UTC, rori4 commented
I have created a separate moon.js (better then adx.js because of adblockers) and I have reverted the initial implementation. We can test out that way the if the validators will reject the requests

2021-01-14 11:42 UTC, Ivshti approved these changes

2021-01-14 13:42 UTC, IvoPaunov approved these changes

2021-01-14 14:45 UTC, Ivshti approved these changes

2021-01-14 14:46 UTC, merged